<?php 
	$auto = $this->getConfig('auto');
	$speed = $this->getConfig('speed');
	$default = $this->getConfig('itemsDefault');
	$desktop = $this->getConfig('itemsDesktop');
	$desktop_small = $this->getConfig('itemsDesktopSmall');
	$tablet = $this->getConfig('itemsTablet');
	$mobile = $this->getConfig('itemsMobile');
	$show_next_back = $this->getConfig('next_back');
	$show_navigation_control = $this->getConfig('nav_ctrl');

	use Magento\Framework\App\Action\Action;
	if($this->getConfig('enabled')){ // start enable module?>
		<?php $_productCollection = $this->getProducts();
	$_helper = $this->helper('Magento\Catalog\Helper\Output');	
?>
<div class="rokan-bestseller section-element section-product">		
	<?php			
		if ($block->getMode() == 'grid') {
			$viewMode = 'grid';
			$image = 'category_page_grid';
			// $showDescription = false;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
		} else {
			$viewMode = 'list';
			$image = 'category_page_list';
			// $showDescription = true;
			$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
		}
		$pos = $block->getPositioned();			
	?>
	<?php if($this->getConfig('title')){?>
		<div class="rokan-product-heading rokan-featured-heading"><h2><?php echo $this->getConfig('title')?></h2>
			<p class="description">
				<?php echo $this->getConfig('subtitle')?>
			</p>
		</div>
	<?php }?>
	<div  class="row">
		<div class="col-xs-12 col-sm-6 col-md-4 col-lg-6">
			<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_bestsellers_home5')->toHtml(); ?>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-8 col-lg-6">
			<?php if(!$_productCollection->getSize()): ?> 
			<div class="rokan-featured-slider">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = $this->getConfig('row_show');
			?>	
			<div class="row">
				<ul class="owl">
					<?php $_collectionSize = $_productCollection->count() ?>
					<?php $i=0; foreach ($_productCollection as $_product): ?>
						<?php if($i %$rows == 0) echo "<li class='item bestsellerslider-item'>"; ?>
							<div class="product-item">
							<div class="item">
								<?php
								$newFromDate = $_product->getNewsFromDate();
								$newToDate = $_product->getNewsToDate();                 
								$now = date("Y-m-d H:m(worry)");
								// Get the Special Price
								$specialprice = $_product->getSpecialPrice(); 
								// Get the Special Price FROM date
								$specialPriceFromDate = $_product->getSpecialFromDate();
								// Get the Special Price TO date
								$specialPriceToDate = $_product->getSpecialToDate();
								// Get Current date
								?>
								<?php
								$productImage = $block->getImage($_product, $image);
								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								}
								?>
								<div class="product-photo">
									<?php // Product Image ?>
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php $productImageThumb = $block->getImage($_product, 'category_page_grid-1-m');?> 
										<span class="image0 image-switch">
											<?php echo $productImage->toHtml(); ?>
										</span>
										<span class="image1 image-switch">
											<?php echo $productImageThumb->toHtml(); ?>
										</span>
									</a>
									<?php if ($this->helper('Rokanthemes\QuickView\Helper\Data')->isEnable()){ ?>			
											<div class="quickview-product">
													<a href="javascript:void(0)" data-role="quickview-button" data-id="<?php echo $_product->getId(); ?>" data-href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_product->getId()) ?>" title="<?php echo $block->escapeHtml(__('Quick view')); ?>" class="ajax diamond tooltip-hover" data-placement="top" data-original-title="<?php echo ('Quick view') ?>"><span><?php echo __('Quick view') ?></span></a>
											</div>
										<?php } ?>	
											
									<div class="product-label">
										<?php
											if ($specialprice&&($specialPriceFromDate <= $now && $specialPriceToDate >= $now)){
												echo "<span class='onsale'>Sale</span>";
												}else{
												if($newFromDate <= $now && $newToDate >= $now) {
													echo "<span class='newlabel'>New</span>";
													//echo $now.' -- '.$newsFrom.' -- '.$newsTo;
												}
											}
										?>	
									</div>
								</div>
								<div class="product-info">
								<div class="product-category">
										<?php
										$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
										$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
										$adapter = $resource->getConnection();
										$categories = $_product->getCategoryIds();
										$count = false;
										foreach($categories as $key=>$category){
										$sql = 'SELECT parent_id FROM catalog_category_entity WHERE entity_id = "'.$category.'"';
										$data = $adapter->fetchRow($sql);
										if($data['parent_id']){
										$cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
										if($cat->getLevel() != 1){ ?>
										<a href="<?php echo $cat->getUrl() ?>"><?php echo $cat->getName(); ?></a>
										<?php $count = true;
										}

										}
										?>
										<?php if($count){ break; }?>
										<?php } ?>
										</div>
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<strong class="product name product-item-name product-name">
									<a class="product-item-link"
									   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</strong>

								<?php if ($templateType): ?>
										<?php echo $block->getReviewsSummaryHtml($_product, $templateType,true); ?>
									<?php endif; ?>
								<div class="product-price-and-shipping">	
									<?php if( $this->getConfig('show_price') ): ?>
										 <?php /* @escapeNotVerified */ echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getPriceDisplayCustom($block->getProductPrice($_product)) ?>
									<?php endif; ?>
									<?php if ( $_product->getFinalPrice() < $_product->getPrice() ): ?>
										<div class="hot-onsale">
											<span class="onsale">
												<span class="sale-text"><?php echo $block->showLableSalePrice($_product); ?>
												</span>
											</span>
										</div>
									<?php endif; ?>
								</div>
								
								</div>									
							<?php $i++;?>
						</div>
						</div>
						<?php if($i %$rows == 0) echo "</li>"; ?>                  
					<?php endforeach; ?>
						<?php if($i %$rows != 0) echo "</li>"; ?>                
				</ul>
			</div>
		</div>
	</div>
	
	<?php if (!$block->isRedirectToCartEnabled()) : ?>
		<script type="text/x-magento-init">
		{
			"[data-role=tocart-form], .form.map.checkout": {
				"catalogAddToCart": {}
			}
		}
		</script>
	<?php endif; ?>
		<script>
			require([
				'jquery',
				'mage/mage',
				'rokanthemes/owl'
			], function ($) {
				'use strict';

				jQuery(".rokan-bestseller .owl").owlCarousel({
					lazyLoad: true,
					autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
					items : <?php echo $default; ?>,
					itemsDesktop : [1199,<?php echo $desktop; ?>],
					itemsDesktopSmall : [991,<?php echo $desktop_small; ?>],
					itemsTablet: [767,<?php echo $tablet; ?>],
					itemsMobile : [480,<?php echo $mobile; ?>],
					slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
					paginationSpeed : 500,
					rewindSpeed : 500,
					navigation : <?php if($show_next_back) echo 'true'; else echo 'false'; ?>,
					stopOnHover : true,
					pagination :false,
					scrollPerPage:true,
				});
			});
		</script>
<?php endif; ?>
</div>
<?php } ?>