<?php
$showWishlist = true;
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();
			
            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    default:
        $exist = null;
}
?>

<?php if ($exist):?>
<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php if ($type == 'related'): ?>
<section class="block <?php echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php else: ?>
<section class="block <?php echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
<?php endif; ?>
<?php else: ?>
<section class="block <?php echo $class; ?>">
   <?php endif; ?>
	<div class="rokan-product-heading"> 
		<h2><?php echo $title; ?></h2>
		<?php if ($type == 'related' && $canItemsAddToCart) :?>
			<div class="block-actions">
				<?= $block->escapeHtml(__('Check items to add to the cart or')) ?>
				<button type="button" class="action select" data-role="select-all"><span><?= $block->escapeHtml(__('select all')) ?></span></button>
			</div>
		<?php endif; ?>		
	</div>
	<div class="block-content content owl-product" aria-labelledby="block-<?php echo $class?>-heading">
		<div class="row">
			<div id="relate_product_slider_<?php echo $type;?>" class="owl-carousel">
				<?php $iterator = 1; ?>
				<?php 
					$i = 0;
					$rows = 1;
				?>
				<?php foreach ($items as $_item): ?>
				<?php $available = ''; ?>
				<?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
				<?php if (!$_item->getRequiredOptions()): ?>
				<?php $available = 'related-available'; ?>
				<?php endif; ?>
				<?php endif; ?>
			<?php
					$productImage = $block->getImage($_item, $image);
			?>	
				<?php if ($i++%$rows==0) { ?>
					<div class="product-item">
				<?php } ?>
					<div class="item">
						<div class="product-photo">
							<a href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php $productImageThumb = $block->getImage($_item, 'category_page_grid-1');?>
								<span class="image0 image-switch">
									<?php echo $productImage->toHtml(); ?>
								</span>
								<span class="image1 image-switch">
									<?php echo $productImageThumb->toHtml(); ?> 
								</span>
							</a>
							<div class="actions-add-cart">
								<div class="action-inner">
										
									<ul class="add-to-links">
										<?php if ($canItemsAddToCart && !$_item->isComposite() && $_item->isSaleable() && $type == 'related') :?>
										<li>
										<?php if (!$_item->getRequiredOptions()) :?>
											<div class="field choice related">
												<input type="checkbox" class="checkbox related" id="related-checkbox<?= $block->escapeHtmlAttr($_item->getId()) ?>" name="related_products[]" value="<?= $block->escapeHtmlAttr($_item->getId()) ?>" />
												<label class="label" for="related-checkbox<?= $block->escapeHtmlAttr($_item->getId()) ?>"><i class="icon-shopping-bag"></i></label>
											</div>
										<?php endif; ?>
										</li>
									<?php endif; ?>	
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
										<li>
											<a href="#"
											   class="action button towishlist"
											   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
											   data-action="add-to-wishlist"
											   role="button">
												
											</a>
										</li>
										<?php endif; ?>										
										
										<?php
											$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); 
										?>
										<li><a href="#"
											   class="action button tocompare"
											   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
											   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'
											   role="button">
												
											</a>
										</li>	
									</ul>
								</div>	
							</div>	
							<div class="product-label">
								<?php if ( $_item->getFinalPrice() < $_item->getPrice() ): ?>
									<span class="onsale">
										<span class="sale-bg"></span>
										<span class="sale-text"><?php echo __('Sale') ?></span>
									</span>
								<?php endif; ?>
								<?php $todayDate = time(); 
									$timeStartNew = strtotime($_item->getData('news_from_date'));
									$timeEndNew = strtotime($_item->getData('news_to_date')); ?>
								<?php if ( $timeEndNew >= $todayDate && $timeStartNew <= $todayDate): ?>
									<span class="newlabel">
										<span><?php echo __('New') ?></span>
									</span>
								<?php endif; ?>
							</div>
						</div>
						<div class="product-info">
							<div class="product-category">
										<?php 
										$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
										$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
										$adapter  = $resource->getConnection();
										$categories = $_item->getCategoryIds(); 
										$count = false;
										foreach($categories as $key=>$category){
											$sql = 'SELECT parent_id FROM catalog_category_entity WHERE entity_id = "'.$category.'"';
											$data = $adapter->fetchRow($sql);
											if($data['parent_id']){
												$cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category); 
												if($cat->getLevel() != 1){ ?>
													<a href="<?php echo $cat->getUrl() ?>"><?php  echo $cat->getName(); ?></a>
													<?php $count = true;
												}
												
											}
										?> 
											<?php if($count){ break; }?>
										<?php	} ?> 
							</div>					
							<strong class="product name">
								<a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->getProductUrl($_item) ?>">
								<?php echo $block->escapeHtml($_item->getName()) ?></a>
							</strong>
							<div class="product-ratting-common">
							<?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
							</div>
							<?php echo $block->getProductPrice($_item); ?>						
						</div>

					</div> 
				<?php if($i%$rows==0 || $i == count($items)) { ?> 
				</div> 
				<?php } ?>
				<?php endforeach ?>
			</div>
		</div>
    </div>

</section>
<?php endif;?>
<script type="text/javascript">
	require([
		'jquery',
		'mage/mage',
		'rokanthemes/owl'
	], function ($) {
		'use strict';

		jQuery("#relate_product_slider_<?php echo $type;?>").owlCarousel({
			lazyLoad: true,
			autoPlay : false,
			items : 5,
			itemsDesktop : [1199,4],
			itemsDesktopSmall : [980,3],
			itemsTablet: [768,2],
			itemsMobile : [479,1],
			slideSpeed : 500,
			paginationSpeed : 500,
			rewindSpeed : 500,
			navigation : true,
			stopOnHover : true,
			pagination :false,
			scrollPerPage:true,
		});
	});
</script>