<div class="share">
	<span class="categories-label"><?php /* @escapeNotVerified */ echo __('Share');?> </span>
	<div class="add-share">
	<!-- AddThis Button BEGIN -->
		<div class="addthis_toolbox addthis_default_style ">
		<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
		<a class="addthis_button_tweet"></a>
		<a class="addthis_button_pinterest_pinit" pi:pinit:layout="horizontal"></a>
		<a class="addthis_counter addthis_pill_style"></a>
		</div>
		<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-538d2d303ab3eaa0"></script>
	<!-- AddThis Button END -->
		<div style="clear:both"></div>
	</div>
</div>